server:
  port: 8080

spring:
  application:
    name: gateway-api

  groovy:
    template:
      cache: false

  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/products/**
        - id: client-service
          uri: http://localhost:8083
          predicates:
            - Path=/clients/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"   # Your frontend URL
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
